Use latest `vc-test-suite-implementations` repo and change test suite tag names.
w3c/vc-di-eddsa-test-suite pull request #24
Opened 2023-11-16 20:11 UTC by JSAssassin

2023-11-19 21:38 UTC, dlongley approved these changes

2023-11-20 16:52 UTC, BigBlueHat approved these changes

2023-11-20 19:06 UTC, TallTed requested changes
Tiny. Plural noun takes plural verb.

2023-11-22 21:20 UTC, aljones15 approved these changes
LGTM

2023-11-25 05:13 UTC, TallTed approved these changes

2023-11-27 21:26 UTC, merged